plugins {
    id 'java'
    id 'application'
    id 'io.spring.javaformat' version '0.0.39'
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}

application {
    mainClass = 'app.GicCinemasApp'
}

repositories { 
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:6.0.2'
}

test { 
    useJUnitPlatform() 
}
